### ISSUE TITLE
Fade time

### ISSUE THREAD

**Issue by grizcreative** [bitfocus/companion-module-generic-artnet#1]
A fade time to go from 0 to set value, or even better would be a fade time between starting value and ending value

**Comment by killianbc** [comment]
Also interested in this feature: an adjustable fade time for each action
I added a small bounty:
https://www.bountysource.com/issues/92785573-fade-time

**Comment by killianbc** [comment]
This feature has already been implemented in a similar module: companion-module-generic-sacn  (but currently with some issues)
https://github.com/bitfocus/companion-module-generic-sacn/blob/5f848954c840910b61ccb809bffbfa59ed53c0b4/sacn.js#L242

**Comment by Julusian** [comment]
Implemented in #3
