### ISSUE TITLE
artnet: Set Value by Custom Variable

### ISSUE THREAD

**Issue by frabusas** [bitfocus/companion-module-generic-artnet#4]
Hi, the values of the variables for "Channel", "Value" and "Fade Time" are fixed when the key is first executed. Is this an error, is it deliberately programmed this way or am I possibly doing something wrong?

![image](https://user-images.githubusercontent.com/67244165/204162490-9cfa2982-be1b-462a-ad24-5d91054c34a0.png)

![image](https://user-images.githubusercontent.com/67244165/204162543-52eef03d-c8c5-4349-a8a2-e23fcb6ea90e.png)

**Comment by Julusian** [comment]
This should be fixed now in the betas. If there is a 2.4.2 release it will be fixed there too
